<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue</name>
   <tag></tag>
   <elementGuidId>78383588-3765-4207-bc4c-28b160a4f333</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;action&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='action']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>01853c62-ea77-42ca-89c1-18746a2f2acd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c2db6874-a990-4ad7-9974-c2ac5c8f8160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>action</value>
      <webElementGuid>2d5f2b4a-8419-45ee-95a6-ad9e00f132b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>54132a15-3bda-4dbf-be31-5ebeaa98bea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ca1f3bf53 c9c234f8c c602d2620 c5046538e cfbf2acec</value>
      <webElementGuid>c67233ff-1b77-4ba5-abeb-5f3d8ea6d047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>63398860-d3a6-4db5-a9b8-7f74b38fd2e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;c3681f759 c18791ed5&quot;]/main[@class=&quot;c1afb972a mfa-webauthn-challenge&quot;]/section[@class=&quot;c9037684a _prompt-box-outer cc5326c6c&quot;]/div[@class=&quot;c3558750d c4c4b0ced&quot;]/div[@class=&quot;c24a0321c&quot;]/div[@class=&quot;ulp-awaiting-action-outer&quot;]/div[@class=&quot;c07c62d27 c99664d50&quot;]/button[@class=&quot;ca1f3bf53 c9c234f8c c602d2620 c5046538e cfbf2acec&quot;]</value>
      <webElementGuid>653aa41b-0e04-4658-ad5a-7ec4ca89a9b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='action']</value>
      <webElementGuid>5c41c19e-1a7e-44d6-9c29-de0f132ba6dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remember this device for 30 days'])[1]/following::button[1]</value>
      <webElementGuid>6e733ac9-e3d3-475b-89bb-df0806e5efe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Awaiting device confirmation'])[1]/following::button[1]</value>
      <webElementGuid>f5118dc6-130d-4874-a5d1-1f4ac4c573ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Try another method'])[1]/preceding::button[1]</value>
      <webElementGuid>8848292a-0af4-4781-86c0-46f4b403fc6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue']/parent::*</value>
      <webElementGuid>7f8f2d3e-2488-41ab-8ac9-33d7be069479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>8ed02984-7c85-4628-a6e6-7854c353eaf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'action' and (text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>863b6a25-9349-4c8d-8ad2-0dc5e8390324</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
