<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue</name>
   <tag></tag>
   <elementGuidId>5db14370-75df-4bb1-9d15-cc8ab503c298</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;action&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='action']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ca36e6bf-15d3-48be-b471-687277887c87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>67e69ee8-7f6e-4059-9136-4cf8ee6cb29e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>action</value>
      <webElementGuid>8d72c9c9-9513-45a0-8a2b-7cc38d9a459f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>43b003e7-e273-4122-8d7b-2944f93e253d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ca1f3bf53 c9c234f8c c602d2620 cc8ffda57 c51c3a06d</value>
      <webElementGuid>da978d08-65c0-4a58-bd5b-44db9cc8e098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>ca2801bd-f442-4fc0-82d9-b40e2b4add2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;c3681f759 c18791ed5&quot;]/main[@class=&quot;c1afb972a login&quot;]/section[@class=&quot;c9037684a _prompt-box-outer cc5326c6c&quot;]/div[@class=&quot;c3558750d c4c4b0ced&quot;]/div[@class=&quot;c24a0321c&quot;]/div[@class=&quot;c07c62d27 c99664d50&quot;]/form[@class=&quot;cd25424d6 c4f61dc66&quot;]/div[@class=&quot;c90e953d1&quot;]/button[@class=&quot;ca1f3bf53 c9c234f8c c602d2620 cc8ffda57 c51c3a06d&quot;]</value>
      <webElementGuid>24379f33-5f3a-46e3-a997-84b0743fe553</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='action']</value>
      <webElementGuid>1f20bb88-db26-4111-bd9b-39d161798ca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot password?'])[1]/following::button[1]</value>
      <webElementGuid>61ee1981-84de-41ac-93fa-367ea1b25bdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hide password'])[2]/following::button[1]</value>
      <webElementGuid>f7ac5dd4-1ec5-45a4-aaa2-cffe2a7ba7e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Or'])[1]/preceding::button[1]</value>
      <webElementGuid>3d3f918f-9347-47bf-b1ec-12ffc4452ce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue with Google (OAuth)'])[1]/preceding::button[1]</value>
      <webElementGuid>6151c179-fb78-4627-a010-4cc8283383dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue']/parent::*</value>
      <webElementGuid>50b5d4bf-6d77-46cd-8177-bd28555e47c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>a64ed16a-7ac9-419c-9663-585289edb148</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'action' and (text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>e6085f7d-b5e0-41ea-b1fc-8da44a52e462</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
